// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: services/grpc/protobuf/event_sync.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_ERROR   ReturnCode = 0
	ReturnCode_SUCCESS ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ReturnCode_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_grpc_protobuf_event_sync_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_services_grpc_protobuf_event_sync_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{0}
}

type DepositToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositToken) Reset() {
	*x = DepositToken{}
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositToken) ProtoMessage() {}

func (x *DepositToken) ProtoReflect() protoreflect.Message {
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositToken.ProtoReflect.Descriptor instead.
func (*DepositToken) Descriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{0}
}

func (x *DepositToken) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *DepositToken) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *DepositToken) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *DepositToken) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DepositToken) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositToken) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DepositTokensReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	Page          uint64                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokensReq) Reset() {
	*x = DepositTokensReq{}
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokensReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokensReq) ProtoMessage() {}

func (x *DepositTokensReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokensReq.ProtoReflect.Descriptor instead.
func (*DepositTokensReq) Descriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{1}
}

func (x *DepositTokensReq) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *DepositTokensReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepositTokensReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DepositTokenListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=theweb3.event.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DepositToken  []*DepositToken        `protobuf:"bytes,3,rep,name=deposit_token,json=depositToken,proto3" json:"deposit_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokenListRep) Reset() {
	*x = DepositTokenListRep{}
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokenListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokenListRep) ProtoMessage() {}

func (x *DepositTokenListRep) ProtoReflect() protoreflect.Message {
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokenListRep.ProtoReflect.Descriptor instead.
func (*DepositTokenListRep) Descriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{2}
}

func (x *DepositTokenListRep) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *DepositTokenListRep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DepositTokenListRep) GetDepositToken() []*DepositToken {
	if x != nil {
		return x.DepositToken
	}
	return nil
}

type DepositTokenDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"` //类似JWT
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokenDetailReq) Reset() {
	*x = DepositTokenDetailReq{}
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokenDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokenDetailReq) ProtoMessage() {}

func (x *DepositTokenDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokenDetailReq.ProtoReflect.Descriptor instead.
func (*DepositTokenDetailReq) Descriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DepositTokenDetailReq) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *DepositTokenDetailReq) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type DepositTokenDetailRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=theweb3.event.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Guid          string                 `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,5,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Sender        string                 `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        uint64                 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokenDetailRep) Reset() {
	*x = DepositTokenDetailRep{}
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokenDetailRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokenDetailRep) ProtoMessage() {}

func (x *DepositTokenDetailRep) ProtoReflect() protoreflect.Message {
	mi := &file_services_grpc_protobuf_event_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokenDetailRep.ProtoReflect.Descriptor instead.
func (*DepositTokenDetailRep) Descriptor() ([]byte, []int) {
	return file_services_grpc_protobuf_event_sync_proto_rawDescGZIP(), []int{4}
}

func (x *DepositTokenDetailRep) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *DepositTokenDetailRep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DepositTokenDetailRep) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *DepositTokenDetailRep) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *DepositTokenDetailRep) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *DepositTokenDetailRep) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DepositTokenDetailRep) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositTokenDetailRep) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_services_grpc_protobuf_event_sync_proto protoreflect.FileDescriptor

const file_services_grpc_protobuf_event_sync_proto_rawDesc = "" +
	"\n" +
	"'services/grpc/protobuf/event_sync.proto\x12\rtheweb3.event\"\xb8\x01\n" +
	"\fDepositToken\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x04R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\"j\n" +
	"\x10DepositTokensReq\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x04R\bpageSize\"\xa0\x01\n" +
	"\x13DepositTokenListRep\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.theweb3.event.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\rdeposit_token\x18\x03 \x03(\v2\x1b.theweb3.event.DepositTokenR\fdepositToken\"R\n" +
	"\x15DepositTokenDetailReq\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\"\x8a\x02\n" +
	"\x15DepositTokenDetailRep\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.theweb3.event.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\tR\x04guid\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x05 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06sender\x18\x06 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\a \x01(\x04R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp*$\n" +
	"\n" +
	"ReturnCode\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x012\xd3\x01\n" +
	"\fEventService\x12\\\n" +
	"\x13getDepositTokenList\x12\x1f.theweb3.event.DepositTokensReq\x1a\".theweb3.event.DepositTokenListRep\"\x00\x12e\n" +
	"\x15getDepositTokenDetail\x12$.theweb3.event.DepositTokenDetailReq\x1a$.theweb3.event.DepositTokenDetailRep\"\x00B\x19Z\x17./services/grpc/eventpbb\x06proto3"

var (
	file_services_grpc_protobuf_event_sync_proto_rawDescOnce sync.Once
	file_services_grpc_protobuf_event_sync_proto_rawDescData []byte
)

func file_services_grpc_protobuf_event_sync_proto_rawDescGZIP() []byte {
	file_services_grpc_protobuf_event_sync_proto_rawDescOnce.Do(func() {
		file_services_grpc_protobuf_event_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_grpc_protobuf_event_sync_proto_rawDesc), len(file_services_grpc_protobuf_event_sync_proto_rawDesc)))
	})
	return file_services_grpc_protobuf_event_sync_proto_rawDescData
}

var file_services_grpc_protobuf_event_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_grpc_protobuf_event_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_grpc_protobuf_event_sync_proto_goTypes = []any{
	(ReturnCode)(0),               // 0: theweb3.event.ReturnCode
	(*DepositToken)(nil),          // 1: theweb3.event.DepositToken
	(*DepositTokensReq)(nil),      // 2: theweb3.event.DepositTokensReq
	(*DepositTokenListRep)(nil),   // 3: theweb3.event.DepositTokenListRep
	(*DepositTokenDetailReq)(nil), // 4: theweb3.event.DepositTokenDetailReq
	(*DepositTokenDetailRep)(nil), // 5: theweb3.event.DepositTokenDetailRep
}
var file_services_grpc_protobuf_event_sync_proto_depIdxs = []int32{
	0, // 0: theweb3.event.DepositTokenListRep.code:type_name -> theweb3.event.ReturnCode
	1, // 1: theweb3.event.DepositTokenListRep.deposit_token:type_name -> theweb3.event.DepositToken
	0, // 2: theweb3.event.DepositTokenDetailRep.code:type_name -> theweb3.event.ReturnCode
	2, // 3: theweb3.event.EventService.getDepositTokenList:input_type -> theweb3.event.DepositTokensReq
	4, // 4: theweb3.event.EventService.getDepositTokenDetail:input_type -> theweb3.event.DepositTokenDetailReq
	3, // 5: theweb3.event.EventService.getDepositTokenList:output_type -> theweb3.event.DepositTokenListRep
	5, // 6: theweb3.event.EventService.getDepositTokenDetail:output_type -> theweb3.event.DepositTokenDetailRep
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_grpc_protobuf_event_sync_proto_init() }
func file_services_grpc_protobuf_event_sync_proto_init() {
	if File_services_grpc_protobuf_event_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_grpc_protobuf_event_sync_proto_rawDesc), len(file_services_grpc_protobuf_event_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_grpc_protobuf_event_sync_proto_goTypes,
		DependencyIndexes: file_services_grpc_protobuf_event_sync_proto_depIdxs,
		EnumInfos:         file_services_grpc_protobuf_event_sync_proto_enumTypes,
		MessageInfos:      file_services_grpc_protobuf_event_sync_proto_msgTypes,
	}.Build()
	File_services_grpc_protobuf_event_sync_proto = out.File
	file_services_grpc_protobuf_event_sync_proto_goTypes = nil
	file_services_grpc_protobuf_event_sync_proto_depIdxs = nil
}
