// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: services/grpc/protobuf/event_sync.proto

package eventpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_GetDepositTokenList_FullMethodName   = "/theweb3.event.EventService/getDepositTokenList"
	EventService_GetDepositTokenDetail_FullMethodName = "/theweb3.event.EventService/getDepositTokenDetail"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	GetDepositTokenList(ctx context.Context, in *DepositTokenListReq, opts ...grpc.CallOption) (*DepositTokenListRep, error)
	GetDepositTokenDetail(ctx context.Context, in *DepositTokenDetailReq, opts ...grpc.CallOption) (*DepositTokenDetailRep, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetDepositTokenList(ctx context.Context, in *DepositTokenListReq, opts ...grpc.CallOption) (*DepositTokenListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositTokenListRep)
	err := c.cc.Invoke(ctx, EventService_GetDepositTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetDepositTokenDetail(ctx context.Context, in *DepositTokenDetailReq, opts ...grpc.CallOption) (*DepositTokenDetailRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositTokenDetailRep)
	err := c.cc.Invoke(ctx, EventService_GetDepositTokenDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations should embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	GetDepositTokenList(context.Context, *DepositTokenListReq) (*DepositTokenListRep, error)
	GetDepositTokenDetail(context.Context, *DepositTokenDetailReq) (*DepositTokenDetailRep, error)
}

// UnimplementedEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) GetDepositTokenList(context.Context, *DepositTokenListReq) (*DepositTokenListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositTokenList not implemented")
}
func (UnimplementedEventServiceServer) GetDepositTokenDetail(context.Context, *DepositTokenDetailReq) (*DepositTokenDetailRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositTokenDetail not implemented")
}
func (UnimplementedEventServiceServer) testEmbeddedByValue() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_GetDepositTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositTokenListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetDepositTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetDepositTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetDepositTokenList(ctx, req.(*DepositTokenListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetDepositTokenDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositTokenDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetDepositTokenDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetDepositTokenDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetDepositTokenDetail(ctx, req.(*DepositTokenDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theweb3.event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getDepositTokenList",
			Handler:    _EventService_GetDepositTokenList_Handler,
		},
		{
			MethodName: "getDepositTokenDetail",
			Handler:    _EventService_GetDepositTokenDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/grpc/protobuf/event_sync.proto",
}
